services:
  server:
    container_name: Tryora-server
    env_file:
      - ./server/.env
    environment:
      # REMOVE the manual EMAIL_HOST, USER, and PASS lines
      - NODE_ENV=development
      - PORT=8000
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "npx prisma migrate deploy && npm run dev"
    volumes:
      - ./server:/app
      - /app/node_modules

  worker:
    container_name: Tryora-worker
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
    command: npm run worker:dev
    volumes:
      - ./server:/app
      - /app/node_modules
