services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: Tryora-server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - path: ./server/.env
        required: false

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: Tryora-worker
    command: node worker.js
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - path: ./server/.env
        required: false

networks:
  default:
    name: Tryora-network

