import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { randomUUID } from 'node:crypto';
import logger from '#src/config/logger.ts';
import {
  GeneratedImageStorageInput,
  GeneratedImageStorageResult,
} from '#src/types/image.js';
import {
  buildImageObjectKey,
  buildUploadThingFileName,
  downloadImageBytes,
  getS3Config,
  inferExtension,
  trimTrailingSlash,
  uploadToUploadThing,
} from '#src/utils/image/image.ts';

const uploadToS3 = async (
  bytes: Buffer,
  objectKey: string,
  contentType: string
): Promise<GeneratedImageStorageResult> => {
  const config = getS3Config();

  const s3 = new S3Client({
    region: config.region,
    endpoint: config.endpoint,
    forcePathStyle: Boolean(config.endpoint),
    credentials: {
      accessKeyId: config.accessKeyId,
      secretAccessKey: config.secretAccessKey,
    },
  });

  await s3.send(
    new PutObjectCommand({
      Bucket: config.bucket,
      Key: objectKey,
      Body: bytes,
      ContentType: contentType,
    })
  );

  const publicBase =
    process.env.AWS_S3_PUBLIC_BASE_URL?.trim() ||
    process.env.R2_PUBLIC_BASE_URL?.trim() ||
    (config.endpoint
      ? `${trimTrailingSlash(config.endpoint)}/${config.bucket}`
      : `https://${config.bucket}.s3.${config.region}.amazonaws.com`);

  return {
    provider: 's3',
    key: objectKey,
    url: `${trimTrailingSlash(publicBase)}/${objectKey}`,
  };
};

const inferExtensionFromMimeType = (contentType: string) => {
  if (contentType.includes('jpeg')) {
    return 'jpg';
  }

  if (contentType.includes('webp')) {
    return 'webp';
  }

  if (contentType.includes('png')) {
    return 'png';
  }

  return 'png';
};

export const storeGeneratedImageBytesToOwnedStorage = async (input: {
  bytes: Buffer;
  contentType: string;
  sourceLabel?: string;
}): Promise<GeneratedImageStorageResult> => {
  const safeContentType = input.contentType || 'image/png';
  const extension = inferExtensionFromMimeType(safeContentType);
  const sourceReference = `${input.sourceLabel || 'gemini'}:${randomUUID()}`;
  const objectKey = buildImageObjectKey(sourceReference, extension);
  const fileName = buildUploadThingFileName(objectKey);

  try {
    const uploadThingResult = await uploadToUploadThing(
      input.bytes,
      fileName,
      safeContentType
    );

    logger.info(
      `[Image Storage] Stored generated bytes in UploadThing (${uploadThingResult.key})`
    );

    return uploadThingResult;
  } catch (uploadThingError) {
    logger.warn(
      `[Image Storage] UploadThing upload failed for generated bytes; falling back to S3: ${String(uploadThingError)}`
    );
  }

  const s3Result = await uploadToS3(input.bytes, objectKey, safeContentType);

  logger.info(`[Image Storage] Stored generated bytes in S3 (${s3Result.key})`);

  return s3Result;
};

export const mirrorGeneratedImageToOwnedStorage = async (
  input: GeneratedImageStorageInput
): Promise<GeneratedImageStorageResult> => {
  const { bytes, contentType } = await downloadImageBytes(input.sourceUrl);
  const extension = inferExtension(input.sourceUrl, contentType);
  const objectKey = buildImageObjectKey(input.sourceUrl, extension);
  const fileName = buildUploadThingFileName(objectKey);

  try {
    const uploadThingResult = await uploadToUploadThing(
      bytes,
      fileName,
      contentType
    );

    logger.info(
      `[Image Storage] Mirrored generated image to UploadThing (${uploadThingResult.key})`
    );

    return uploadThingResult;
  } catch (uploadThingError) {
    logger.warn(
      `[Image Storage] UploadThing upload failed; falling back to S3: ${String(uploadThingError)}`
    );
  }

  const s3Result = await uploadToS3(bytes, objectKey, contentType);

  logger.info(
    `[Image Storage] Mirrored generated image to S3 (${s3Result.key})`
  );

  return s3Result;
};
