// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const env = process.env.NODE_ENV || "development";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env === "development" ? process.env["DATABASE_URL_LOCAL"] : process.env["DATABASE_URL_CLOUD"],
  },
});
